### ISSUE TITLE
Top 5 weapons - wrong output?

### ISSUE THREAD

**Issue by itzhaki** [SecretSquirrel001/Planetside-Intel#5]
My character (itzhaki) shows the Solstice VE3 in the top 5 weapons, while I have way more kills on other weapons. I'm guessing you are choosing the top 5 by score and not kills? That's a problem because if I'm using boosts while playing 1 weapon, and not on the other, so that's changes the score I can get. How about switching to kills?

**Comment by SecretSquirrel001** [comment]
thats a good point! :+1:  I will see what I can do! :)

**Comment by SecretSquirrel001** [comment]
I have changed the top 5 weapon to go based off of kills instead of score :+1: 

The Changes will be visible during the next big update that is being worked on now
