### ISSUE TITLE
Auraxium medals show up as Gold (less kills)

### ISSUE THREAD

**Issue by itzhaki** [SecretSquirrel001/Planetside-Intel#6]
Hi again :)
My char names (itzhaki) has 1,155 kills on the Beamer and I already have the Auraxium medal. This happens because SOE is missing some stats before the API was introduced. I know that http://stats.dasanfall.com/ somehow fixes it and on their website it does show my beamer with Auraxium medal. Can it be fixed?

**Comment by SecretSquirrel001** [comment]
I am not sure how they did it personally :( they could be just adding extra kills to weapons to give it a boost? I am not sure :(
